version: '3.7'

services:
  swift_writers:
    build:
      context: .
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      SECRET_KEY: 'secret-key'
      DJANGO_SETTINGS_MODULE: swift_writers.settings.development
      DATABASE_NAME: swift_writers-db-name
      DATABASE_USER: swift_writers-db-user
      DATABASE_PASSWORD: swift_writers-db-pwd
      POSTGRES_IP: db
    depends_on:
      - db
  db:
    image: postgres:12.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: swift_writers-db-pwd
      POSTGRES_USER: swift_writers-db-user
      POSTGRES_DB: swift_writers-db-name

volumes:
  postgres_data:
