# Generated by Django 3.1.6 on 2021-04-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210423_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'PLACED'), ('confirmed', 'CONFIRMED'), ('healthy', 'HEALTHY'), ('unhealthy', 'UNHEALTHY'), ('dangerous', 'DANGEROUS'), ('critical', 'CRITICAL'), ('indeterminate', 'INDETERMINATE'), ('cancelled', 'CANCELLED'), ('delivered', 'DELIVERED'), ('finished', 'FINISHED')], error_messages={'required': 'Please provide the status for this order.'}, max_length=40),
        ),
    ]
