# Generated by Django 3.1.6 on 2021-04-26 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import order.models.order_material


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_auto_20210423_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.FileField(upload_to=order.models.order_material.user_directory_path)),
                ('extension', models.CharField(blank=True, default='N/A', max_length=20, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='order.order')),
            ],
        ),
    ]
