# Generated by Django 3.1.6 on 2021-04-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_tempordermaterial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tempordermaterial',
            options={'ordering': ('date_uploaded',)},
        ),
    ]
