# Generated by Django 3.1.6 on 2021-05-01 07:48

from django.db import migrations, models
import order.models.temp_order_material


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210430_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempordermaterial',
            name='material',
            field=models.FileField(error_messages={'required': 'Please provide the material.'}, upload_to=order.models.temp_order_material.temp_material_directory_path),
        ),
    ]
